# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    hello  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""

from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
    "certifi >= 14.5.14",
    "frozendict ~= 2.3.4",
    "python-dateutil ~= 2.7.0",
    "setuptools >= 21.0.0",
    "typing_extensions ~= 4.3.0",
    "urllib3 ~= 1.26.7",
]

setup(
    name=NAME,
    version=VERSION,
    description="Swagger Petstore - OpenAPI 3.0",
    author="OpenAPI Generator community",
    author_email="apiteam@swagger.io",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Swagger Petstore - OpenAPI 3.0"],
    python_requires=">=3.7",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description="""\
    hello  # noqa: E501
    """
)
