# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    hello  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""

import unittest

import openapi_client
from openapi_client.model.tag import Tag
from openapi_client import configuration


class TestTag(unittest.TestCase):
    """Tag unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
