# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    hello  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.pet.post import AddPet
from openapi_client.paths.pet_pet_id.delete import DeletePet
from openapi_client.paths.pet_find_by_status.get import FindPetsByStatus
from openapi_client.paths.pet_find_by_tags.get import FindPetsByTags
from openapi_client.paths.pet_pet_id.get import GetPetById
from openapi_client.paths.pet.put import UpdatePet
from openapi_client.paths.pet_pet_id.post import UpdatePetWithForm
from openapi_client.paths.pet_pet_id_upload_image.post import UploadFile


class PetApi(
    AddPet,
    DeletePet,
    FindPetsByStatus,
    FindPetsByTags,
    GetPetById,
    UpdatePet,
    UpdatePetWithForm,
    UploadFile,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
