# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    hello  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.store_order_order_id.delete import DeleteOrder
from openapi_client.paths.store_inventory.get import GetInventory
from openapi_client.paths.store_order_order_id.get import GetOrderById
from openapi_client.paths.store_order.post import PlaceOrder


class StoreApi(
    DeleteOrder,
    GetInventory,
    GetOrderById,
    PlaceOrder,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
