# coding: utf-8

"""
    Swagger Petstore - OpenAPI 3.0

    hello  # noqa: E501

    The version of the OpenAPI document: 1.0.11
    Contact: apiteam@swagger.io
    Generated by: https://openapi-generator.tech
"""

from openapi_client.paths.user.post import CreateUser
from openapi_client.paths.user_create_with_list.post import CreateUsersWithListInput
from openapi_client.paths.user_username.delete import DeleteUser
from openapi_client.paths.user_username.get import GetUserByName
from openapi_client.paths.user_login.get import LoginUser
from openapi_client.paths.user_logout.get import LogoutUser
from openapi_client.paths.user_username.put import UpdateUser


class UserApi(
    CreateUser,
    CreateUsersWithListInput,
    DeleteUser,
    GetUserByName,
    LoginUser,
    LogoutUser,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
